### PR TITLE
Added page links into the main nav bar

### PR DESCRIPTION
**Pull request by ShawnJohnston**
All changes were in the NavMenu.js file. Not all of them will stay on the nav bar permanently, and some would be visible/invisible depending on state.

"Create booking,", "View My Listings", "Search", "Appointments", "Messages", "My Profile", "Account", ""Login", "Register", "Logout"

### CODE REVIEW

**Comment by ShawnJohnston** [comment]
Added commit create skeleton component files for the new nav menu items that require their own dedicated page. Added them to the AppRoutes.js file.

**Comment by ShawnJohnston** [comment]
Initial login page HTML added. No styles or functionality.

**Comment by ShawnJohnston** [comment]
Added some Bootstrap styling to login page. Added link under login button to redirect user to register page.

**Comment by ShawnJohnston** [comment]
Created registration form for the register page. Most necessary details. Setting business accounts as admin or not is not included yet.

Initial Bootstrap styling.

**Review by grtn316 — APPROVED** [review]
Update looks good. There is 1 non blocking error on the login page:

image

Approving as this will get resolved when the page is fully implemented.

**Review by grtn316 — APPROVED** [review]
lgtm

**Pull request merged**
